// Blog posts data
export const blogPosts = [
  {
    id: "1",
    title: " A critical treatment of Christology in the works of Calvin",
    date: "April 28, 2024",
    author: "Dr. Esckindr Tadesse",
    category: "Article",
    description: "The following reflection is on the Christological summary of Calvin from his book \"Institutes of Christian Religion, Book II, Chapter xiii, paragraph 4 through Book II, chapter xiv, paragraphs 1-3.\"",
    image: "/images/programs/Calvin 2.jpg",
  },
  {
    id: "2",
    title: " A critical treatment of Christology in the works of Charles Hodge",
    date: "April 28, 2024",
    author: "Dr. Esckindr Tadesse",
    category: "Article",
    description: "The following reflection is on the Christological summary of reflection on Charles Hodge From his book of \"Systematic Theology, vol II, part II. ch III, pages 387-418 ; 433-440.\"",
    image: "/images/programs/Charles2.jpg",
  },
  {
    id: "3",
    title: "An Introduction to African Philosophy: Review",
    date: "April 29, 2024",
    author: "Alemayehu Hotessa",
    category: "Article",
    description: "The following Artice is a book review on the book 'An Introduction to Africana Philosophy' by Lewis R. Gordon.",
    image: "/images/programs/African.jpg",
  },
  {
    "id": "4",
    "title": "How Africa Shaped The Christian Mind",
    "date": "April 29, 2024",
    "author": "Pr. Simeneh Teklu",
    "category": "Article",
    "description": "This article reviews the book 'How Africa Shaped The Christian Mind' by Thomas C. Oden, exploring the profound influence of African intellect and culture on the development of early Christianity.",
    "image": "/images/programs/Africa 2.jpg",
  },
  { 
    "id": "5",
    "title": "The Role of Religious Language Games Within the Ethiopian Orthodox Tewhado Church: A Search for Hermeneutic Principles in the Future Reconstruction of Interpretative Approaches",
    "date": "October 2021",
    "author": "Dr. Esckinder Taddesse",
    "category": "Article",
    "description": "This article explores the role of religious language games in the Ethiopian Orthodox Tewhado Church (EOTC), proposing a new hermeneutic to restore its spiritual identity and unity by centering Jesus Christ as the root metaphor.",
    "image": "/images/programs/Orthodox.jpg",
  },
  {
    "id": "6",
    "title": "Martin Heidegger and the Foundations of Modern Thought: A Review",
    "date": "October 12, 2020",
    "author": "Ghebrehiwot Tesfazghi",
    "category": "Article",
    "description": "This article reviews Timothy Clark's 'Martin Heidegger' (Taylor and Francis e-Library, 2001), exploring Heidegger's profound influence on modern thought, his critique of Western metaphysics, and his impact on theology and poetics.",
    "image": "/images/programs/Heidegger.jpg",
  },
  {
    "id": "7",
    "title": "Rhetoric: An Historical Introduction - A Review",
    "date": "May 15, 2022",
    "author": "Berhanu Bonora",
    "category": "Article",
    "description": "This article reviews Wendy Olmsted's 'Rhetoric: An Historical Introduction,' exploring the historical development of rhetoric as a practical art of deliberation and judgment, its classical roots, and its relevance to contemporary disciplines.",
    "image": "/images/programs/Rhetoric 2.jpg",
  },
  {
    "id": "8",
    "title": "Martin Heidegger: Routledge Critical Thinkers - A Review",
    "date": "May 15, 2022",
    "author": "Berhanu Bonora",
    "category": "Article",
    "description": "This article reviews Timothy Clark's 'Martin Heidegger' in the Routledge Critical Thinkers series, examining Heidegger's profound influence on modern thought, his engagement with art and language, and his controversial legacy.",
    "image": "/images/programs/Heidegger-Critical.jpg",
  },
  {
    "id": "9",
    "title": "An Introduction to Second Temple Judaism: A Review",
    "date": "May 15, 2022",
    "author": "Berhanu Bonora",
    "category": "Article",
    "description": "This article reviews Lester L. Grabbe's 'An Introduction to Second Temple Judaism,' providing an overview of the history and religion of the Jews from the Persian period to the Bar Kokhba revolt, with a focus on the diverse currents within Judaism during this era.",
    "image": "/images/programs/Second Temple.jpg",
  },
  {
    "id": "10",
    "title": "Twentieth Century Theology: God & the World in a Transitional Age - A Review",
    "date": "May 15, 2022",
    "author": "Berhanu Bonora",
    "category": "Article",
    "description": "This article reviews Stanley J. Grenz and Roger E. Olson's 'Twentieth Century Theology,' exploring the dynamic interplay between divine transcendence and immanence in theological developments from the Enlightenment to the postmodern era.",
    "image": "/images/programs/20th Century.jpg",
  },
  {
    "id": "11",
    "title": "Defending God: Biblical Responses to the Problem of Evil - A Review",
    "date": "July, 2024",
    "author": "Abenezer Eshetu",
    "category": "Article",
    "description": "This article reviews James L. Crenshaw’s 'Defending God: Biblical Responses to the Problem of Evil,' exploring biblical perspectives on theodicy and the complex interplay between divine justice, human suffering, and theological responses to evil.",
    "image": "/images/programs/Defending-God.jpg",
  },
  {
    "id": "12",
    "title": "The Myth of Religious Neutrality - A Review",
    "date": "Feb 3, 2012",
    "author": "Dr. Esckinder Taddesse",
    "category": "Article",
    "description": "This article reviews Roy A. Clouser's 'The Myth of Religious Neutrality: An Essay on the Hidden Role of Religious Belief in Theories,' exploring the interplay between theories, religious beliefs, and their impact on science, philosophy, and religion.",
    "image": "/images/programs/Religious-Neutrality.jpg",
  },
]